# Generated by Django 2.2 on 2020-12-22 03:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hg_app', '0004_auto_20201220_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='url',
        ),
        migrations.RemoveField(
            model_name='video',
            name='url',
        ),
        migrations.AddField(
            model_name='image',
            name='img',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='img'),
        ),
        migrations.AddField(
            model_name='video',
            name='vid',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='vid'),
        ),
    ]
