# Generated by Django 2.2 on 2020-12-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hg_app', '0005_auto_20201221_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='cards', to='hg_app.Image'),
        ),
    ]
