# Generated by Django 2.2 on 2020-12-27 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hg_app', '0007_image_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='hg_app.Video'),
        ),
    ]
