# Generated by Django 2.2 on 2021-01-04 15:41

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hg_app', '0009_card_unique_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('aud', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='aud')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='card',
            name='unique_id',
            field=models.CharField(default='99203', max_length=10),
        ),
        migrations.AddField(
            model_name='card',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='hg_app.Audio'),
        ),
    ]
