# Generated by Django 2.2 on 2021-01-05 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hg_app', '0010_auto_20210104_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='unique_id',
            field=models.CharField(default='47358', max_length=10),
        ),
    ]
