# Generated by Django 2.2 on 2021-01-06 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hg_app', '0011_auto_20210104_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio_mgs', to='hg_app.User'),
        ),
        migrations.AddField(
            model_name='video',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_mgs', to='hg_app.User'),
        ),
        migrations.AlterField(
            model_name='card',
            name='unique_id',
            field=models.CharField(default='32014', max_length=10),
        ),
    ]
