# Generated by Django 2.2 on 2021-01-06 05:17

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hg_app', '0013_auto_20210105_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='aud',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='aud'),
        ),
        migrations.AlterField(
            model_name='card',
            name='unique_id',
            field=models.CharField(default='35754', max_length=10),
        ),
    ]
