# Generated by Django 2.2 on 2021-01-06 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hg_app', '0014_auto_20210105_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='unique_id',
            field=models.CharField(default='23209', max_length=10),
        ),
    ]
