# Generated by Django 2.2 on 2021-01-07 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hg_app', '0015_auto_20210105_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='granted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='unique_id',
            field=models.CharField(default='16117', max_length=10),
        ),
    ]
