# Generated by Django 2.2 on 2021-01-07 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hg_app', '0016_auto_20210106_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='user_likes',
            field=models.ManyToManyField(related_name='liked_posts', to='hg_app.User'),
        ),
        migrations.AlterField(
            model_name='card',
            name='unique_id',
            field=models.CharField(default='19931', max_length=10),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='hg_app.Card')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='hg_app.User')),
            ],
        ),
    ]
