# Generated by Django 2.2 on 2021-01-09 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hg_app', '0017_auto_20210107_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='message',
            new_name='card',
        ),
        migrations.AlterField(
            model_name='card',
            name='unique_id',
            field=models.CharField(default='77337', max_length=10),
        ),
        migrations.AlterField(
            model_name='comment',
            name='poster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='hg_app.User'),
        ),
    ]
