# Generated by Django 2.2 on 2021-01-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hg_app', '0018_auto_20210109_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='receiver_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='receiver_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='unique_id',
            field=models.CharField(default='62848', max_length=10),
        ),
    ]
