# Generated by Django 2.2 on 2021-01-09 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hg_app', '0020_auto_20210109_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='unique_id',
            field=models.CharField(default='59250', max_length=10),
        ),
        migrations.AlterField(
            model_name='comment',
            name='poster',
            field=models.CharField(default='nothing', max_length=100),
            preserve_default=False,
        ),
    ]
