# Generated by Django 2.2 on 2021-01-09 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hg_app', '0021_auto_20210109_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='card',
            name='unique_id',
            field=models.CharField(default='53352', max_length=10),
        ),
    ]
