# Generated by Django 2.2 on 2021-01-10 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hg_app', '0022_auto_20210109_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='unique_id',
            field=models.CharField(default='31111', max_length=10),
        ),
    ]
